name: Deploy documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Create virtual environment
        run: |
          python3 -m venv "$HOME/s3prl_env"
          echo "$HOME/s3prl_env/bin" >> $GITHUB_PATH

      - name: install S3PRL
        run: |
          pip install -e ".[dev]"

      - name: Build doc
        run: |
          cd docs/
          ./rebuild_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html

